name: Build Canabalt

on: [push, workflow_dispatch]

jobs: 
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                submodules: recursive
                token: ${{ secrets.GH_TOKEN }}

            - uses: krdlab/setup-haxe@v1
              with:
                haxe-version: 4.3.3
            - name: Install HMM
              run: |
                haxelib install hmm --quiet
            - name: Download Haxelibs
              run: |
                haxelib run hmm install --quiet
            - name: Build
              run: |
                haxelib run lime build html5 -debug
            - name: Archive production artifacts
              uses: actions/upload-artifact@v4
              with:
                name: canabalt-html5
                path: |
                    export/html5/bin/
            - name: Get current date
              id: date
              run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
            - uses: vimtor/action-zip@v1.1
              with:
                files: export/html5/bin/
                dest: canabalt-html5-${{ steps.date.outputs.date }}.zip
            - name: Github Releases Upload
              uses: marvinpinto/action-automatic-releases@v1.2.1
              with:
                repo_token: "${{ github.token }}"
                automatic_release_tag: "latest"
                prerelease: true
                title: "Canabalt Bleeding edge"
                files: |
                    canabalt-html5-${{ steps.date.outputs.date }}.zip
                    LICENSE.md
                    assets/LICENSE.md
                
                